name: CI Pipeline
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["dev"]

jobs:
  run-tests:
    name: Run generic PowerShell tests
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run generic tests (PowerShell)
        shell: pwsh
        run: |
          pwsh -File ./test.ps1
